version: "3.8"

services:
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/etc:/etc/letsencrypt
  #     - ./certbot/var:/var/lib/letsencrypt
  #     - ./certbot/html:/var/www/html
  #   depends_on:
  #     - proxy
  #   command: certonly --webroot --webroot-path=/var/www/html --email info@aistudybuddy.se --agree-tos --staging -d d0018e.aistudybuddy.se
  #   # command: certonly --webroot --webroot-path=/var/www/html --email info@aistudybuddy.se --force-renewal --agree-tos -d d0018e.aistudybuddy.se
  proxy:
    container_name: store-proxy
    image: macbre/nginx-http3:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
      - ./certbot/html:/var/www/html
      - ./dhparam:/etc/ssl/certs
    networks:
      - d0018e
    depends_on:
      - cache
  cache:
    image: varnish:alpine
    container_name: store-cache
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl:ro
    ports:
      - 8080:80
    depends_on:
      - web
    networks:
      - d0018e
    environment:
      - VARNISH_SIZE=512M
  web:
    image: store-web:latest
    container_name: store-web
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file: .env.local
    depends_on:
      - db
    networks:
      - d0018e
    # Port not exposed as it is proxied through nginx
    ports:
      - "3000:3000"
  db:
    container_name: store-db
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - d0018e

volumes:
  my-db:

networks:
  d0018e:
    driver: bridge
