version: "3.8"

services:
  reverse-proxy:
    container_name: store-proxy
    image: nginx:1.25.3
    ports:
      - 80:80
    volumes:
      - ./static/eggs:/var/www/eggs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
  web:
    image: store-web:latest
    container_name: store-web
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file:
      - .env.local
    depends_on:
      - db
    # Port not exposed as it is proxied through nginx
    # ports:
    #   - "3000:3000"
  db:
    container_name: store-db
    image: mysql:5.7
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
